"use client";

import { FormEvent, useState } from "react";
import { caseStudies, services, techGroups, projects } from "../data/portfolio";

const siteUrl = "https://your-domain.example";

const Arrow = () => <span aria-hidden="true">→</span>;
const Icon = ({ name }: { name: string }) => <span className="service-icon" aria-hidden="true">{name}</span>;

function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy?: string }) {
  return <header className="section-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="lead">{copy}</p>}</header>;
}

function ContactForm() {
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  return <form className="contact-form" onSubmit={submit}>
    <div className="form-grid"><label>Name<input required name="name" autoComplete="name" placeholder="Your name" /></label><label>Email<input required name="email" type="email" autoComplete="email" placeholder="you@company.com" /></label><label>Company <em>optional</em><input name="company" autoComplete="organization" placeholder="Company name" /></label><label>Budget range <em>optional</em><select name="budget"><option value="">Select a range</option><option>Under $1,000</option><option>$1,000–$3,000</option><option>$3,000+</option><option>Let’s discuss</option></select></label></div>
    <label>What do you need help with?<input required name="help" placeholder="Deployment, cloud setup, CI/CD, production issue…" /></label>
    <label>Message<textarea required name="message" rows={4} placeholder="A little context about the application, current setup, or issue would help." /></label>
    <label className="urgent"><input type="checkbox" name="urgent" /> <span><strong>I need urgent production help</strong><small>This flags the request; it does not imply 24/7 support.</small></span></label>
    <button className="button primary" type="submit">{sent ? "Thanks — add your contact handler" : "Start a conversation"} <Arrow /></button>
    {sent && <p className="form-note">This demo form is ready to connect to your email or form provider. See the README.</p>}
  </form>;
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeCase, setActiveCase] = useState(0);
  const active = caseStudies[activeCase];
  return <>
    <header className="nav"><a className="brand" href="#home" aria-label="Umair Malik home"><b>UM</b><span>Umair Malik<small>DevOps / Cloud</small></span></a><button className="menu" aria-expanded={menuOpen} aria-controls="nav-links" onClick={() => setMenuOpen(!menuOpen)}>Menu</button><nav id="nav-links" className={menuOpen ? "open" : ""}><a href="#services">Services</a><a href="#work">Work</a><a href="#about">About</a><a href="#contact" className="nav-cta">Let’s talk <Arrow /></a></nav></header>
    <main id="home">
      <section className="hero wrap"><div className="hero-copy"><p className="status"><i /> Available for freelance / contract work</p><p className="eyebrow">DEVOPS ENGINEER · PAKISTAN</p><h1>I build and maintain the infrastructure behind <em>production applications.</em></h1><p className="hero-lead">Cloud infrastructure, Docker, CI/CD, Linux servers, AWS, deployments, and production troubleshooting — for teams that need systems to work reliably.</p><div className="actions"><a className="button primary" href="#contact">Let’s work together <Arrow /></a><a className="button ghost" href="#work">View my work</a></div><a className="linkedin" href="https://www.linkedin.com/in/umair-ops/" target="_blank" rel="noreferrer">LinkedIn <Arrow /></a></div>
        <div className="pipeline" aria-label="Illustration of deployment pipeline"><div className="pipeline-top"><span>deployment-flow.yml</span><i>● LIVE</i></div>{["Developer", "Git", "CI / CD", "Docker", "Cloud", "Production"].map((node, index) => <div className="pipe-node" key={node}><span>{String(index + 1).padStart(2,"0")}</span><b>{node}</b>{index < 5 && <i>↓</i>}</div>)}<div className="terminal"><span>$</span> deploy --environment production<br/><strong>✓ release verified</strong></div></div>
      </section>
      <section className="capability"><div className="wrap"><span>APPLICATION → INFRASTRUCTURE → PRODUCTION</span><p>I help turn a working application into a dependable production system.</p><span>CALM UNDER PRESSURE</span></div></section>
      <section className="wrap intro" id="services"><SectionHeading eyebrow="WHAT I ACTUALLY DO" title="Your application works. Now let’s make production work." copy="Getting software live means more than uploading code. I work across the server, containers, database, domain, and deployment process so the whole system works together — and stays understandable." /><div className="outcomes"><div><b>01</b><h3>Get it deployed</h3><p>Take an application from a developer’s laptop to a real, secure production environment.</p></div><div><b>02</b><h3>Find what’s broken</h3><p>Trace difficult failures across code, services, infrastructure, and configuration.</p></div><div><b>03</b><h3>Make releases repeatable</h3><p>Replace manual release steps with reliable, documented deployment workflows.</p></div></div></section>
      <section className="wrap services"><SectionHeading eyebrow="SERVICES" title="Infrastructure that supports the work your team is doing." /><div className="service-grid">{services.map(s => <article className="service-card" key={s.title}><Icon name={s.symbol} /><h3>{s.title}</h3><p>{s.description}</p><span>{s.tags.join(" · ")}</span></article>)}</div></section>
      <section className="work-section" id="work"><div className="wrap"><SectionHeading eyebrow="REAL PROBLEMS I’VE SOLVED" title="Production work is rarely a clean slate." copy="A selection of real infrastructure and deployment situations. Each one is presented as an engineering incident, not a generic project card." /><div className="incident-layout"><div className="incident-list" role="tablist" aria-label="Case studies">{caseStudies.map((item, i) => <button key={item.title} role="tab" aria-selected={activeCase === i} className={activeCase === i ? "selected" : ""} onClick={() => setActiveCase(i)}><span>INC-{String(i + 1).padStart(3,"0")}</span>{item.title}<Arrow /></button>)}</div><article className="incident" role="tabpanel"><p className="incident-status">● RESOLVED · CASE STUDY</p><h3>{active.title}</h3><div className="incident-flow"><div><span>01 / PROBLEM</span><p>{active.problem}</p></div><div><span>02 / INVESTIGATION</span><p>{active.investigation}</p></div><div><span>03 / SOLUTION</span><p>{active.solution}</p></div><div><span>04 / RESULT</span><p>{active.result}</p></div></div><footer>{active.technologies.map(t => <code key={t}>{t}</code>)}</footer></article></div></div></section>
      <section className="wrap projects"><SectionHeading eyebrow="PROJECTS" title="Application work, kept truthful." copy="Project cards are structured for public work and confidential engagements. Add project details and verified links as they become available." /><div className="project-grid">{projects.map(project => <article key={project.name} className="project-card"><div><span>{project.private ? "CONFIDENTIAL" : "PROJECT"}</span><i>◌</i></div><h3>{project.name}</h3><p>{project.description}</p><p className="contribution"><b>Contribution</b>{project.role}</p><footer>{project.technologies.map(t => <code key={t}>{t}</code>)}</footer></article>)}</div></section>
      <section className="architecture"><div className="wrap"><SectionHeading eyebrow="UNDER THE HOOD" title="A production path I’m comfortable working across." copy="Hover or focus a system layer to see where it fits. Exact architecture changes with the application; the goal is a clear, reliable path to production." /><div className="arch-grid">{[{n:"01",t:"GitHub",d:"Source, reviews, and release history."},{n:"02",t:"GitHub Actions",d:"Build, test, and deployment automation."},{n:"03",t:"Docker Build",d:"Repeatable application environments."},{n:"04",t:"Registry",d:"Versioned container images."},{n:"05",t:"Server / Swarm",d:"The runtime environment and services."},{n:"06",t:"Nginx",d:"Production traffic, domains, and TLS."},{n:"07",t:"App + Data",d:"Application, PostgreSQL, MySQL, or Redis."}].map(x=><div className="arch-node" tabIndex={0} key={x.t}><span>{x.n}</span><b>{x.t}</b><p>{x.d}</p></div>)}</div></div></section>
      <section className="wrap tech"><SectionHeading eyebrow="TECHNOLOGY STACK" title="Tools in context, not a logo wall." /><div className="tech-groups">{techGroups.map(group => <article key={group.name}><h3>{group.name}</h3><div>{group.items.map(item => <span className={item.level === "foundational" ? "foundational" : ""} key={item.name}>{item.name}{item.level === "foundational" && <small>foundation</small>}</span>)}</div></article>)}</div></section>
      <section className="process wrap"><SectionHeading eyebrow="HOW I WORK" title="Methodical when the system is unfamiliar." /><ol>{["Understand|I inspect the current application and infrastructure instead of making assumptions.","Diagnose|I trace problems across code, servers, containers, databases, networking, DNS, and deployments.","Fix|I implement the smallest reliable solution that addresses the underlying problem.","Automate|Where appropriate, I turn manual work into repeatable deployments and infrastructure.","Document|I leave the environment understandable and maintainable for the team."].map((x,i)=>{const [t,d]=x.split("|");return <li key={t}><b>0{i+1}</b><div><h3>{t}</h3><p>{d}</p></div></li>})}</ol></section>
      <section className="about" id="about"><div className="wrap about-grid"><div><p className="eyebrow">ABOUT UMAIR</p><h2>Systems thinking, brought to software infrastructure.</h2></div><div><p>I started in Electrical Engineering and moved into software infrastructure and DevOps. That transition taught me to learn unfamiliar systems quickly and approach technical problems from a systems perspective.</p><p>I enjoy Linux, networking, automation, cloud systems, troubleshooting, and making deployments repeatable — the work that helps application teams move with more confidence.</p><div className="facts"><span><b>2+ years</b>DevOps experience</span><span><b>BS Electrical Engineering</b>COMSATS University Islamabad</span></div></div></div></section>
      <section className="trust wrap"><SectionHeading eyebrow="WHY CLIENTS WORK WITH ME" title="Practical infrastructure support, without the theater." /><div>{[["Practical experience","Real servers, containers, databases, deployments, and production environments."],["Troubleshooting mindset","I follow the problem through the system, not just the first error message."],["Application awareness","Enough application context to understand how code and infrastructure affect each other."],["Clear communication","Technical findings explained clearly for both engineering teams and stakeholders."],["Adaptable approach","Comfortable entering an existing environment and learning its moving parts."]].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section>
      <section className="contact" id="contact"><div className="wrap contact-grid"><div><p className="eyebrow">START A CONVERSATION</p><h2>Have an infrastructure problem? <em>Let’s fix it.</em></h2><p>Whether you’re deploying a new application, fighting a production issue, or cleaning up an existing setup, send me the details.</p><a href="https://www.linkedin.com/in/umair-ops/" target="_blank" rel="noreferrer" className="button ghost">Connect on LinkedIn <Arrow /></a></div><ContactForm /></div></section>
    </main><footer className="footer wrap"><div><b>Umair Malik</b><span>DevOps Engineer · Cloud & Infrastructure</span></div><div><a href="https://www.linkedin.com/in/umair-ops/" target="_blank" rel="noreferrer">LinkedIn</a><span>GitHub — add URL</span><span>Email — add address</span><span>Resume — add link</span></div><small>© {new Date().getFullYear()} Umair Malik</small></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify({"@context":"https://schema.org","@type":"Person",name:"Umair Malik",jobTitle:"DevOps Engineer",url:siteUrl,sameAs:["https://www.linkedin.com/in/umair-ops/"],knowsAbout:["Cloud infrastructure","Docker","CI/CD","AWS","Linux servers"]})}} />
  </>;
}
